### ISSUE TITLE
Make læreglede section responsive

### ISSUE THREAD

**Issue by petterhh** [varianter/variant.no#1033]

**Comment by mikaelbr** [comment]
I think this is solved now 🤔

**Comment by petterhh** [comment]
> I think this is solved now 🤔

@mikaelbr The image still disappears on smaller resolutions 😢 
<img width="988" alt="Image" src="https://github.com/user-attachments/assets/44895cae-a6f1-4fc0-8f91-0bf965e89365" />

I tried to replicate the wrapping from [the designs](https://www.figma.com/design/zgXtEvibcgxxvdMDBBaICD/Ny-variant.no%2Fse?node-id=5599-35408&m=dev) by using `flex-wrap: wrap`, `max-width` etc, but couldn't get it to work

**Comment by mikaelbr** [comment]
Aah. Thats the issue. I thought maybe it was intentional. Can fix but I dont think it is very critical for tomorrow
