### ISSUE TITLE
Horisontal scroll i Chrome Windows

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#11]
Det er en konteiner som er bredere enn den burde være / en overflow hidden som ikke er satt som gjør at det blir horisontal scroll på variant.no i Chrome for Windows. Ser ikke særlig bra ut.

**Comment by jakobsen** [comment]
Bekreftes i Firefox på mac også.

Jeg har forsøkt å titte litt på denne i dag, og det virker som om det er i alle fall to elementer det er problemer med: [`.career__header__illustration`](https://github.com/varianter/variant.no/blob/f842505d12b57679044ee24a5cb2e8112938ca81/index.html#L114) og [`.blog__illustration`](https://github.com/varianter/variant.no/blob/f842505d12b57679044ee24a5cb2e8112938ca81/index.html#L381-L383).

Jeg gikk frem ved å legge til linjen `border: solid 1px red !important` under `*, *:before, *:after`-selectoren i [style.css](https://github.com/varianter/variant.no/blob/f842505d12b57679044ee24a5cb2e8112938ca81/assets/style.css), for å gjøre det lettere å se hvilke elementer som går utenfor siden. Dette viser at de nevnte elementene flyter over, og ved å kommentere dem ut fra [index.html](https://github.com/varianter/variant.no/blob/f842505d12b57679044ee24a5cb2e8112938ca81/index.html) gjør at den horisontale skrollingen forsvinner. Om en da fjerner de røde rammene fra alle elementene kommer den horisontale skrollingen tilbake, uten at jeg forstår hvorfor.

**Comment by mikaelbr** [comment]
Hei! Takk for bra tips og at du har sett på dette! Mistenker at det er den topp-skrå-stripene i toppen som forårsaker det på et vis. Bra tips med border der. Lurer på om det også kunne vært bra å bruke `outline` fremfor `border` da `outline` ikke tar en del av view layout og du ikke vil få en del "false negatives".

Men! Er i prosess om å redesigne hele variant.no til ny profil innen en måneds tid. Så selv om unødvendig horisontal scroll er irriterende, tenker jeg det er like greit å leve med det en måned til enn å bruke for mye tid i å se på det.
