### ISSUE TITLE
Bedre visning av blogg/artikler/innhold

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#203]
Per i dag har vi en seksjon som ser slik ut:

<img width="866" alt="Screenshot 2022-02-16 at 13 54 55" src="https://user-images.githubusercontent.com/606374/154268853-701e8cc4-6501-4a2e-adcc-1cebf05b5a1a.png">

Dette ble endret et tidspunkt for Medium blokkerte mitt reverse engineered API-lag.

Men dette er egentlig en kjedlig og lite nyttig måte å vise innhold på. Vi burde løfte frem aktivitet på innhold (faglig, selskap, endringer, osv) i større grad. Som viser at 1) ting skjer og 2) det gode innholdet forskjellige varianter lager.

Det er mulig å f.eks bruke RSS feeds og parsing av metadata for å få til uthenting dynamisk. Men det må også formes noe god UI/UX som kan løse behovene her.

**Comment by jberglund** [comment]
Vilka fler feeds än dessa kan användas?

Blog: https://blog.variant.no/feed
Intern Podcast: http://podcast.variant.no/feed.xml
Variantsnakk Podcast: https://feeds.transistor.fm/variantsnakk
YouTube: https://www.youtube.com/feeds/videos.xml?channel_id=UCMBx54cKNj8i9R51IE4bfCg
