### ISSUE TITLE
Sikre at variant.no ikke automatisk laster ned podcastepisode på fremsiden

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#229]
Per nå lastes podcast eagerly på variant.no. Det fører til at vi får veldig mange downloads på podcasts. Dette må endres til å kun lastes ned ved trykk på play slik at vi ikke setter kunstig høye lyttertall.

**Comment by trulshj** [comment]
Kan det være podcasten incrementer lyttertall selv om man bare laster inn metadata?

https://www.w3schools.com/tags/att_audio_preload.asp

```html
<!-- elementet som spiller lyden i feeden i dag -->
<audio preload="metadata" ref={audioElement}>
    <source src={url} />
</audio>

<!-- alternativene som preload godtar -->
<audio preload="auto|metadata|none">
    <source src={url} />
</audio>
```
