### ISSUE TITLE
A11y: Color contrast on footer links

### ISSUE THREAD

**Issue by 42tte** [varianter/variant.no#316]
Colors from https://styleguide.variant.no/ have been used for link text & background in footer on variant.no. [These colors do not have enough contrast](https://webaim.org/resources/contrastchecker/?fcolor=E61A6B&bcolor=423D89&api). Need a designer to work out which colors to use in the footer 🙏

![Styleguide-–-Variant](https://user-images.githubusercontent.com/8436510/200170683-627a4007-9f89-47f3-99c1-a5e448d6321e.png)

**Comment by mikaelbr** [comment]
We can probably improve contrasts, but it should be AA compatible, as the footer background on variant.no is `#1A1837`, not `#423D89`. Could also specify better the matching pairs on the style guide is not meant as "use these colors with text" but complementary colors and go together visually.

**Comment by 42tte** [comment]
Good pointing out the correct color. However the text still have too low contrast "Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger." at least on <1470px
