### ISSUE TITLE
Bakgrunnsbildet på håndbok siden kan gjerne bare være hvit farge. 

### ISSUE THREAD

**Issue by tehrafi** [varianter/variant.no#37]
Bakgrunnsbildet på håndbok siden kan gjerne bare være hvit farge. ([https://handbook.variant.no/index.html]

Er bare sjukt rart mens leser/scroller nedover på siden med de ikonene... 

![ikonerhåndbok](https://user-images.githubusercontent.com/37304555/69194605-d0a10680-0b29-11ea-97e5-150a675ac3b5.png)

Ligger her:
.../variant.no/assets/elements/background-pattern.svg

**Comment by mikaelbr** [comment]
Takk for issue! Ja, det var en gang et forsøk på at det skulle se litt mer interessant ut (og å teste ut en kjøpt Sketch plugin), men har også sett at det er forstyrrende. Hele håndboken er nok overmoden for redesign, men inntil da kan vi godt fjerne elementet. 👍 

Ref.: https://github.com/varianter/handbook/pull/80

**Comment by mikaelbr** [comment]
Oppdatert på https://handbook.variant.no/ nå.
