### ISSUE TITLE
Gjøre Mikael enklere å få tak i på svensk

### ISSUE THREAD

**Issue by toretefre** [varianter/variant.no#378]
Enten bør:

- @mikaelbr fjernes fra variant.se
- Telefonnummeret hans prefixes med +47
- Telefon endres til e-post

<img width="393" alt="image" src="https://github.com/varianter/variant.no/assets/21310942/89effcff-0ace-4f21-b488-800003920303">

**Comment by nikolaia** [comment]
Svenske nummer er nå korrekt og Mikael finnes ikke på sida lengre. Problem solved
