### ISSUE TITLE
Navbar på hovedsiden forsvinner tidlig.

### ISSUE THREAD

**Issue by tehrafi** [varianter/variant.no#38]
Navbaren forsvinner rett etter siste rekken med bilder av ansattene.
Det er litt upraktisk mtp at siden er i katogerien "One pager".
Det blir fort altfor mye å scrolling opp om man ønsker å gå helt opp igjen.
Navbaren kan godt være synlig hele veien til footeren.

Bildet viser hvor navbaren forsvinner:
![navbar](https://user-images.githubusercontent.com/37304555/69194914-a7cd4100-0b2a-11ea-8fb2-1dca57fd6d10.png)

**Comment by mikaelbr** [comment]
Takk for denne også!

Det er noe logikk som ligger på når den skal fjernes/skjules. Primært for å ikke overlappe med footer, men ser det er noe offset som kan legges på for at den skal forsvinne nærmere footer. Men jeg tror ikke det er så viktig at header vises når man er på "big footer", og det skal egentlig ikke være så nødvendig å gå helt opp igjen. Det skal være lenker på bunn som tar deg med til de plassen man ønsker å gå, som en slags oppsummering av det man har lest). Om noe kan det være aktuelt med en "til toppen" lenke i footer-området.

For referanse til de interesserte: for å endre hvor den skjules er det kalkulasjon her: https://github.com/varianter/variant.no/blob/master/assets/main.js#L90
