### ISSUE TITLE
https://www.variant.no/ansatte/oslo viser ikke nederst persons kontaktinfo

### ISSUE THREAD

**Issue by haakoaho** [varianter/variant.no#380]
<img width="281" alt="image" src="https://github.com/varianter/variant.no/assets/25222071/fd8fe0f7-527d-4f91-b60e-d555ab08f286">

Knapp som dukker opp på feil sted. Skjer bare med Oslo.

**Comment by nikolaia** [comment]
Har sett dette på andre byer og. Har noe med antall ansatte og gjøre som gjør at når den nederste ansatte er i midten, så får den stillingsblobben over seg
