### ISSUE TITLE
Ukonsistent antall sommerstudenter

### ISSUE THREAD

**Issue by tbwiik** [varianter/variant.no#407]
Antallet sommerstudenter som tas opp er forskjellig på [søknadssiden](https://jobs.variant.no/o/sommerjobb-utvikler-2024/c/new) og siden med [jobbdetaljer](https://www.variant.no/jobs/sommerjobb-utvikler-2024).

Jobbdetalj-side [(repo)](https://github.com/varianter/variant.no/blob/main/src/jobs/pages/sommerjobb-utvikler-2024.md):
<img width="709" alt="Screenshot 2023-09-02 at 16 25 56" src="https://github.com/varianter/variant.no/assets/22935970/5e1c5210-b828-4097-bc37-50a533ea7a6f">

Søknadside:
<img width="1186" alt="Screenshot 2023-09-02 at 16 25 22" src="https://github.com/varianter/variant.no/assets/22935970/2d454a8e-140e-4cff-abb3-8584a7ef4913">

**Comment by mikaelbr** [comment]
Takk for at du gjorde oss oppmerksom på det! @Krakels kan sjekke og korrigere her.

**Comment by Krakels** [comment]
Veldig bra du sier i fra, Torbjørn. Jeg skjønner at det der kan oppfattes forvirrende. Jeg har endret teksten på søknadssiden nå slik at det henger sammen.
