### ISSUE TITLE
Navbar forsvinner bak siden under overgangen fra skrå til rett

### ISSUE THREAD

**Issue by okkero** [varianter/variant.no#42]
Litt pirkete kanskje, men ser litt rart ut at det ikke finnes noen synlig navbar i et lite øyeblikk mens man scroller. Først forsvinner navbaren bak &lt;main&gt; som er nedenfor, også dukker den opp igjen ovenifra når overgangen er ferdig.

<img width="1680" alt="Screenshot 2019-11-27 at 17 57 32" src="https://user-images.githubusercontent.com/4236717/69744907-5f70dd00-1141-11ea-9e69-64eec4c63cdf.png">

<img width="1680" alt="Screenshot 2019-11-27 at 17 57 43" src="https://user-images.githubusercontent.com/4236717/69744916-639cfa80-1141-11ea-9fd9-0009214c367e.png">

**Comment by okkero** [comment]
Har testet litt. Er nok `overflow: hidden` på `.hero` som forårsaker dette. Ser ikke ut til å gå utover andre ting når man fjerner den.

**Comment by jberglund** [comment]
Hejhej!

Först och främst, tack för att du öppnat en issue på det här. Detta ska vi få fixat!

Jag tänkte använda det här svaret för att notera ned vad jag tänkte göra för att fixa det här samt issue #28:


- Skippa `position: fixed` helt. Ta bort negativa värden i förbindelse med `position`. Bör hellre gå för `position: sticky`. 
- För sticky krävs det att nav tas ut från hero. För att sticky ska fungera så måste det ligga i kontexten man scrollar, alltså `body` i detta tillfället.
- Ta bort transition. Custom Properties blir uppdaterade vid scroll, så det blir mindre _awkward_ om man låter värden vara 1:1, utan easing.
- På tal om Custom Properies: eftersom vi har `var(--opacity)` så kan vi hooka upp den till logon så att den gör en bättre övergång. Tänker att det kan göras via `color: rgba(0,0,0,var(--opacity))` eller något liknande.
- Kanske till och med ändra `var(--opacity)` och `var(--rotation)` till något som går från 0 till 100 för att så låta CSS (`calc()`) stå för uträkningen.  
- När man ändå pratar om övergångar så är det värt att nämna att eftersom browsers inte antar att allt kommer att animeras  så tar vi oss friheten att slänga på `will-change: opacity, transform` menyn samt `will-change: color` på logo. Då slipper vi den första yanken som sker precis då transformen laddas in på GPU:n. 60fps+ är nice.

Jag tror det var allt. Blir säkert något mer overflow när man flyttar ut från hero, men tar det som det kommer. Tjobing!
