### ISSUE TITLE
Endring av årstall i lønnskalkulator resettes tilbake til 2017

### ISSUE THREAD

**Issue by hildeor** [varianter/variant.no#45]
Når man forsøker å endre årstall i lønnskalkulatoren, og bekrefter inputverdien, så resettes feltet tilbake til default 2017. 
F. eks ved bruk av enter på pc, eller "Gå" på iOS.

**Comment by jberglund** [comment]
Det borde kanske ha varit en `<input type="range">` istället?

Oavsett så kan vi lägga på `inputmode="numeric" pattern="[0-9]*"` på den inputen vi redan har så får vi en numpad istället för keyboard.

**Comment by jberglund** [comment]
Det resettas fortfarande på desktop om man trycker Enter, men det kan jag leva med. Återställs inte på iOS nu i alla fall.

🥳📈🧮

**Comment by adriansberg** [comment]
Oh no, Android har "Gå"-knapp på numerisk tastatur ser jeg etter en dobbeltsjekk. My bad. 😬
