### ISSUE TITLE
Ha avgjort hvordan vi løser å vise svensk kalkulator

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#477]
Dekker:

- Ha definert hvordan vi kan implementerte Svensk kalkulator

Spørsmål til ettertanke:
- Hvordan definere Linköping vs Stockholm vs Göteborg
- Hva er egentlig pensjon?
- Hvor kommer data fra?

Avhengig av:
- Sverige (David)
- Støtte av Mikael (kanskje Marius på lønn)

**Comment by mikaelbr** [comment]
Denne er done @christinaroise ?

**Comment by christinaroise** [comment]
@mikaelbr yess, den er kun DONE.


Det er så mange ubesvarte spørsmål og løse tråder for både Sverige og Norge at det er hensiktsmessig å ha en egen innsiktsfase og planlegging for kalkulatoren isolert sett. Vi avventer derfor løsning for støtte av flere kalkulatorer. 

Det vi fokuserer på i denne omgang blir da å få eksisterende kalkulator over på ny nettsideløsning, men med forbehold om at det kan legges til flere kalkulatorer i fremtiden. 

Nøyaktig løsning is in the works
