### ISSUE TITLE
Ha en plan og veg fremover for hvordan vi kan støtte både Sverige og Norge (+) i samme løsning

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#512]

**Comment by christinaroise** [comment]
Update: 

The current setup will have two studios configured within the same repository: shared and studio. 

Studio is for unique content related to location (.no vs .se)
Shared has content accessible to both locations (blog, costumer cases, e.g.)

https://github.com/varianter/variant.no/pull/526
