### ISSUE TITLE
Ha kjørende testmiljø til svensk workspace (via Santiy)

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#518]
Vi skal ha kjørende v3.variant.se som går til v3 branch med svensk workspace i Sanity.

- Svensk språk i translations
- Valg av korrekt sanity base

Aktiviteter:

- Legge svensker til tilgang i Sanity (Sara D, Sara H, Daniel, Marco, Andreas B, David D)

**Comment by christinaroise** [comment]
@mikaelbr kan du sette opp v3 mot v3.variant.se og legge meg til i Vercel om jeg ikke alt er det? 

Sanity-prosjektet mot variant.se er satt opp [her](https://www.sanity.io/organizations/ogQnRtwD1/project/wiluj0ex). 

Neste skritt er å legge ved miljønøkler i vercel.

**Comment by christinaroise** [comment]
miljønøkler er lagt til i vercel for .se ✅

**Comment by christinaroise** [comment]
BLOCKED: Vi må lande på en DNS-løsning for styring av de ulike domenene (.no, .se, .dk, .buy-them-all)

**Comment by mikaelbr** [comment]
Egentlig tenker jeg ikke på dette som blocked. Blocked er eksterne faktorer som vi som team ikke har kontroll over og vi rett og slett må vente på. Jeg anser dette med styring av domener og valg av hosting som en del av denne oppgaven og målet om "Vi skal ha kjørende v3.variant.se som går til v3 branch med svensk workspace i Sanity". For at det målet skal nås er det valg som må tas, men det er ingen eksterne faktorer som blokkerer oss fra å ta det valget.

**Comment by christinaroise** [comment]
In short it can be closed, but we want to add some content for .se to "launch" the test environment so to give ownership
