### ISSUE TITLE
Kunne lage innhold på flere språk og la nettsiden fungere på engelsk, svensk og norsk for delt innhold

### ISSUE THREAD

**Issue by christinaroise** [varianter/variant.no#522]
## Bakgrunn og behov

Samme kodebase skal brukes for .se, .no og andre fremtidige land. Disse sidene skal være helt frittstående og uavhengig av hverandre, slik at hvert land har full kontroll over hva som skal vises og hvordan. Dette betyr også at vi må ha støtte for flere språk.

Vi må støtte språk på følgende måter:
- Innholdet generert fra CMS skal kunne være på et konkret språk.
- Elementer brukt i kodebasen (f.eks header, footer, skjema med knapper, kalkulator, osv) skal kunne støtte flere språk. Dette må støtte foreløpig: engelsk, svensk og norsk. Må være enkelt å utvide til flere språk.
- Det er greit å ha UI-språk i kodebasen, men nice to have i CMS. Men det er ikke et absolutt-krav.

## Akseptansekriterier

- [ ] Ikke CMS-styrt innhold skal følge domenet (.se, .no) og ha knapper o.l. på svensk om under .se.
- [ ] Ved overstyring av språk fra valg av bruker skal det settes språk i URL.
- [ ] Språk skal settes primært basert på hvilken side du er på (.se, .no), men kan bruke nettleserinnstillinger til å sette preferanse på innhold.
- [ ] Innenfor .se og .no skal det være mulig å ha innhold på engelsk.
- [ ] Språk skal sendes korrekt til nettleser (lang attribute).

----

Tidligere notater:

Vi tar i bruk Sanitys egen løsning på translations: https://www.sanity.io/docs/localization

Dette vil gi oss mulighet for å oversette innhold som legges inn i Sanity

**Comment by christinaroise** [comment]
Update:

We'll do a mix of localize document and localize fields. For dynamic pages made up of sections, it's best to localize each field within a schema, while for more static like content such as blog posts, costumer cases etc, we can translate on document level.

**Comment by mikaelbr** [comment]
Det er hensiktsmessig å splitte noen krav til eget mål etter design har kommet lengre. Opprett egen oppgave på:

- Innhold som ikke er tilgjengelig på engelsk skal vises, men ha en notis i toppen hvor det står at den ikke er tilgjengelig på engelsk.
- Det skal være mulig å bestemme hvilket språk en vil at UI skal være på.

**Comment by mikaelbr** [comment]
Informasjon delt mellom land (kundecase, etc) vil kunne være ferdig. Må rescope

Parkering: Neste uke kan vi løse det på spesifikke sider.

**Comment by mikaelbr** [comment]
- Mangler UI ting, og ikke koblet shared på klienten.

**Comment by mikaelbr** [comment]
Må prioritere opp "studio" (landsspesifikk) før denne kan fullføres.

**Comment by mikaelbr** [comment]
Scope for denne er å kunne ha en ferdig struktur og oppsett for hvordan språk fungerer i Sanity.
