### ISSUE TITLE
Endring av adresse

### ISSUE THREAD

**Issue by tehrafi** [varianter/variant.no#56]
Slik jeg har forstått det så har dere flyttet og derfor antar jeg besøksadressen er feil, det som står nederst på [jobs-siden](https://jobs.variant.no/)

<img width="1792" alt="jobs" src="https://user-images.githubusercontent.com/37304555/84138032-ec301800-aa4d-11ea-8597-287ca5fa5272.png">

**Comment by oskogstad** [comment]
Bra catch! Skal få oppdatert straks :grin:

**Comment by oskogstad** [comment]
Done!
