### ISSUE TITLE
Automatic redirects after slug changes

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#560]
Slugs can now be changed easily via Sanity Studio. This risks killing shared links using older versions of the page slug.

Proposed solution: Make slug readonly after initial publish

~~Proposed solution:
Every time a slug is changed for a page, a redirection rule should be created to redirect the old to the new slug value.~~

~~Potential issues:~~
~~- Page `A` changes from `/dog` to `/cat`, then page `B` changes from `/cat` to `/dog`. Automatic redirection would redirect `/dog` to `/cat`, making page `B` inaccesible. Or page `B` would take presedence and the old url for page `A` would be broken. So a possible solution would be for active slug values to take presedence, while redirection is a fallback. Ideally a warning should be presented when there are conflicts.~~

**Comment by christinaroise** [comment]
I wonder if we should look into locking the slug as readonly once it's published. And only handle redirect in the redirect document

**Comment by mathiazom** [comment]
Relevant Sanity guide: https://www.sanity.io/guides/nextjs-automatic-redirects

**Comment by mathiazom** [comment]
Closed by #586
