### ISSUE TITLE
Forståelse hvordan brandet vil se ut, jobbe med eksempler

### ISSUE THREAD

**Issue by Likuh** [varianter/variant.no#645]
Sindre jobber med brandet hele uken og oppdaterer meg, på fredag vil vi lage eksempel uttak og teste konseptet han har laget.

**Comment by anemne** [comment]
Presentation of brand: 

https://varianttrh-my.sharepoint.com/personal/te_variant_no/_layouts/15/stream.aspx?id=%2Fpersonal%2Fte%5Fvariant%5Fno%2FDocuments%2FRecordings%2FNew%20visual%20Variant%20brand%20%F0%9F%9A%80%2D20241002%5F113116%2DMeeting%20Recording%2Emp4&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ebe5fe6eb%2Deeca%2D41d9%2Db97c%2Def101a92a931
