### ISSUE TITLE
Stricter ESLint ruleset

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#660]
The ESLint config should extend the following rules instead of the basic `plugin:@typescript-eslint/recommended`:
- `@typescript-eslint/recommended-type-checked`
- `@typescript-eslint/stylistic-type-checked`

**Comment by anemne** [comment]
@mathiazom do we need this, or could we archive this issue?

**Comment by mathiazom** [comment]
> @mathiazom do we need this, or could we archive this issue?

Not important, let's archive it :+1:
