### ISSUE TITLE
FIX - Preview mode not always disabled

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#692]
Preview mode (draft mode) is sometimes not disabled properly, causing some odd data errors (see image). This means that the `__prerender_bypass` cookie is still present even when the user has navigated out of the Presentation tool. Disabling draft mode is currently handled by `AutomaticVisualEditing.tsx`, but does not some to be completely stable.

![Image](https://github.com/user-attachments/assets/3cfad3ba-ce3e-401a-adc4-5370e602c85c)

**Comment by anemne** [comment]
So because it is a http only cookie, I guess we need the server to handle the removal of it?

**Comment by mathiazom** [comment]
Preview mode is very unstable, and I'm afraid we will waste a lot of time trying to fix it. Since it's not a priority, let's ignore it for now 🙈
