### ISSUE TITLE
Support image block in shared richtext

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#699]
Images in rich text from shared are not rendered. This is becuase the image assets are fetched with the studio client, not the shared client.

**Comment by mathiazom** [comment]
A simple solution would be to attempt to fetch with both studio and shared client, and pick whichever it not 404. This assumes that the asset ids are globally unique. 

A more involved, but possibly safer, approach is to pass either a client identifier or the client config itself through the RichText hierarchy. This would require some prop drilling though 👷

**Comment by christinaroise** [comment]
How many layers of prop drilling are we looking at? 🫠

**Comment by mathiazom** [comment]
> How many layers of prop drilling are we looking at? 🫠

- `RichText`
  - `GroupedBlogText`
    - `myPortableTextComponents` (convert to function)
      - `SanityImage`
        - `useConvertSanityImageToNextImage`
          - `SanityImage`

**Comment by christinaroise** [comment]
Hm, could perhpas the RichText component in and of itself be optimized? 🤔 there are also cases where we have myPortableTextComponents because RichText doesnt support normal as any other styles than body, so for cases where we want portable text but with normal as say bodySuperLarge or bodyLarge.. 🤔

**Comment by mathiazom** [comment]
Closed by #702
