### ISSUE TITLE
Proper redirect for URLs with language code

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#720]
Redirects and translations are not mixed perfectly. We should discuss what behaviour we want.

Let's say that `/kalk` redirects to `/kalkulator`, and `/en/calculator` is a translation. Then `/en/kalk` will go to `/kalk` (assuming `/en/kalk` does not exist) which will then go to `/kalkulator` and finally `/en/calculator`. This is only ok if the user has the requested language as preferred, which is not necessarily true.

Redirects should instead be checked for `/en/kalk` (or `/en/calc` if redirects are translated) instead of using the intermediary `/kalk`.

**Comment by anemne** [comment]
This might be relevant: https://www.simeongriggs.dev/nextjs-sanity-slug-patterns

We should discuss whether to use this: https://www.simeongriggs.dev/nextjs-sanity-slug-patterns

**Comment by mathiazom** [comment]
> This might be relevant: https://www.simeongriggs.dev/nextjs-sanity-slug-patterns

I have started to work on supported nested slugs, inspired by this guide. One thing stopping us from storing the whole path for a document in the slug is customer cases. Here we want to be able to have different parent slugs for different studios, so the full path can not be stored in shared. We should still be able to implement proper redirect, it will just be a little more complex 🤠

**Comment by mikaelbr** [comment]
Wont fix. Avoid redirects for now
