### ISSUE TITLE
Create breadcrumb menu

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#798]
Breadcrumb navigation has been completed and is ready for implementation. The next step is to create pages based on the following sketches:
https://www.figma.com/design/zgXtEvibcgxxvdMDBBaICD/Ny-variant.no%2Fse?node-id=1109-4989&t=NTE1FDPIXyoFEe7R-1

Related task: #769

**Comment by mathiazom** [comment]
Closed by #838
