### ISSUE TITLE
Create "Landingsside C" - work

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#806]
This page focused on the "Work With Us" section. The page should include elements as listed in the image below:

- [x] "Employee highlight" (e.g. "Ansattopplevelsen til") of selected employee
  - https://github.com/varianter/variant.no/pull/943
- [x] Open positions and job listings
- Salary calculator module
  - https://github.com/varianter/variant.no/pull/929
- Link to Håndboka with details about company culture and values
  - https://github.com/varianter/variant.no/pull/929
- [x] Contact information to those responsible for recruitment

![Image](https://github.com/user-attachments/assets/a40a7cd2-67ff-437e-8828-c6b8dcd20728)

**Comment by mikaelbr** [comment]
Arbeid for denne:

- Sy sammen blokkene som ligger i Sanity.

**Comment by mikaelbr** [comment]
This could be marked as done now?
