### ISSUE TITLE
Delivery and industry block - predefined values

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#814]
We need to update Sanity with a predefined list of industries and deliverables for users to choose from when creating customer cases. This update will make it easier for users to select relevant options, ensuring consistency and reducing manual entry errors.

![Image](https://github.com/user-attachments/assets/70b8ad14-432c-4475-9ba7-40ba049ad571)

**Comment by anemne** [comment]
What kind of sections industries and deliverables we're adding to the list needs to be discussed.

**Comment by mathiazom** [comment]
How about defining a separate "Tags" document in Sanity, and then add tags for sector and delivery as needed? This would then be shared between countries, with translations. This assumes that the options can be fetched in the relevant pickers when creating a customer case.
