### ISSUE TITLE
Employees in project - UI and logic

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#815]
Each customer case should include a list of employees who have contributed to the project. We need to create mini-profile cards for each employee, linking them to the case. These profile cards should feature essential details (e.g., name, role, photo) and should be displayed as shown in the images below: 

![Image](https://github.com/user-attachments/assets/0755f42a-4a3e-4571-bf2f-278b2523c6a1)
![Image](https://github.com/user-attachments/assets/02f911fc-b27d-4dac-9fa0-b70e6c08e337)

**Comment by mathiazom** [comment]
Should probably specify employees by email (or other readable and sufficiently unique identifier), and then fetch details (name, role, photo) from Chewbacca.

**Comment by mathiazom** [comment]
Closed by #831
