### ISSUE TITLE
Related project - Sanity schema and UI

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#816]
When creating a customer case, we need to add support for linking to other relevant projects. Users should be able to select and link up to three unique, relevant projects from existing customer cases.

This update requires modifications to both the Sanity schema and the UI. 

![Image](https://github.com/user-attachments/assets/38680474-8b0f-4199-8adc-28de0e2cac25)

**Comment by mathiazom** [comment]
Closed by #837
