### ISSUE TITLE
Contact point

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#818]
At the end of each customer case, we should include a designated contact point. This contact could potentially be linked to the existing "Company Locations" schema, allowing users to easily select a relevant contact based on location. 

![Image](https://github.com/user-attachments/assets/99b92932-b167-4c08-a0f4-ac80d67ef79a)

![Image](https://github.com/user-attachments/assets/6a3fcf42-7eb7-4ee4-8a7c-a306c1dbc01d)

**Comment by anemne** [comment]
Do you have any input regarding this @mathiazom or @trulshj?

**Comment by mathiazom** [comment]
Closed by #849
