### ISSUE TITLE
Notification banner

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#819]
The solution should include a notification banner to deliver important messages to visitors on the website. We need to create a dedicated field in Sanity to manage the content of the banner. Initially, the banner should be displayed in customer cases, but it may also be necessary to implement it in other areas of the solution as needed. 

![Image](https://github.com/user-attachments/assets/d8686171-e1fa-4808-bc5b-cea591a272ca)

**Comment by anemne** [comment]
Vi må diskutere hvordan dette skal gjøres. 
Skal vi legge inn flere notifications på engang? 
Hvordan vedlikeholder vi utdaterte notifications? 
Skal vi vise flere notifications på engang, altså slide mellom ulike banners?

**Comment by mathiazom** [comment]
Vi begrenser oss til én melding i første omgang. I tillegg legger vi inn mulighet for å velge "utløpsdato", slik at meldingen skjules etter oppgitt dato og tid.

**Comment by mathiazom** [comment]
Closed by #843
