### ISSUE TITLE
Filtering in employee section

### ISSUE THREAD

**Issue by mathiazom** [varianter/variant.no#825]
Should allow filtering by position and location

https://www.figma.com/design/zgXtEvibcgxxvdMDBBaICD/Ny-variant.no%2Fse?node-id=1143-17263&t=8C5n7426zLyHekL9-4

![Image](https://github.com/user-attachments/assets/7c2725c4-ae8b-4d39-903d-592d95181cc0)

**Comment by mikaelbr** [comment]
Done
