### ISSUE TITLE
Rework the customer case page with new design

### ISSUE THREAD

**Issue by idamand** [varianter/variant.no#882]
https://www.figma.com/design/zgXtEvibcgxxvdMDBBaICD/Ny-variant.no%2Fse?node-id=2530-17465&m=dev

## Acceptance

- [ ] Works on all sizes

**Comment by mikaelbr** [comment]
Farger på resultatblokka, og gjøre mobilvennlig. Kun resultatblokka som er igjen (responsive)

**Comment by mikaelbr** [comment]
This is done in Figma
