### ISSUE TITLE
Add and verify logo salad

### ISSUE THREAD

**Issue by mikaelbr** [varianter/variant.no#966]
Add logos to homepage

**Comment by anemne** [comment]
Design and UI: 
- alignment of logos
- secure that background in svg is transparent. 

In sanity section: 
- edit description
- remove unused fields 
- Validation messages

![Image](https://github.com/user-attachments/assets/69476a55-96da-4425-84da-a39250545d9a)

**Comment by petterhh** [comment]
Snakk med Linn Helen @petterhh 

edit: Done
