### ISSUE TITLE
Control width in sections

### ISSUE THREAD

**Issue by anemne** [varianter/variant.no#967]
Some sections are too narrow. We need to align them with the design. 960px should be replaced with 68rem. 

Control that media queries corresponds with breakpoints in global.css

**Comment by mikaelbr** [comment]
Related: I don't think ALL breakpoints should correspond with variables. Often I think using "local specific" breakpoints adds value. E.g. for container queries. I think following specific break points for specific components can be valuable

**Comment by mikaelbr** [comment]
Also: check padding
